version: "3"
services:
  pythonic_portfolio:
    container_name: Fellowship-Portfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    volumes:
      - .:/Fellowship-Portfolio
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
